/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import javax.swing.ImageIcon;

/**
 *
 * @author Alexander Villasis
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        LoadingBar.setUI(new javax.swing.plaf.basic.BasicProgressBarUI());
        setLocationRelativeTo(null);
        setAlwaysOnTop(true);
        this.setIconImage(new ImageIcon(MainForm.class.getResource("/images/LTOLogo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoadingBar = new javax.swing.JProgressBar();
        Loading = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        SplashScreen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LTO Reservation System");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 800, 10));

        Loading.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        Loading.setForeground(new java.awt.Color(255, 255, 255));
        Loading.setText("  Loading...");
        getContentPane().add(Loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 340, 40));

        LoadingValue.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(255, 255, 255));
        LoadingValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LoadingValue.setText("0%");
        getContentPane().add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 80, 20));

        SplashScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SplashScreen.png"))); // NOI18N
        getContentPane().add(SplashScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Loading;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel SplashScreen;
    // End of variables declaration//GEN-END:variables

    public void getLoadingValue(int i) {
        LoadingValue.setText(i + "%");
    }

    public void getLoading(String string) {
        Loading.setText(string);
    }

    public void getLoadingBar(int i) {
        LoadingBar.setValue(i);
    }
}
